import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import * as esbuild from 'esbuild';
import {fileURLToPath} from 'node:url';
const build=await esbuild.build({entryPoints:[fileURLToPath(new URL('../src/parser.ts',import.meta.url))],bundle:true,write:false,format:'cjs',platform:'node'});
const workerCalls=[];
const context={exports:{},Zotero:{Reader:{_readers:[]},debug(){},PDFWorker:{async getFullText(...args){workerCalls.push(args);return {text:'A'.repeat(300)+'\f'+'B'.repeat(300)+'\f',totalPages:2};}}}};
context.module={exports:context.exports};
vm.runInNewContext(build.outputFiles[0].text,context);context.exports=context.module.exports;
const parsed=await context.exports.parseItem({id:17,getFilePathAsync:async()=>'/paper.pdf'});
assert.equal(workerCalls[0][0],17);
assert.equal(parsed.pages.length,2);assert.equal(parsed.hasPageInfo,true);
assert.equal(context.exports.verifyQuote('this is a sufficiently long original prefix and true ending','this is a sufficiently long original prefix and invented ending'),false);
console.log('PASS: PDFWorker attachment id + page boundaries + whole-quote verification');
const markup=fs.readFileSync(new URL('../addon/chrome/content/settings.xhtml',import.meta.url),'utf8');
const ids=[...markup.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const elements=new Map(ids.map(id=>[id,{value:'',checked:false,style:{},addEventListener(){}}]));
let mounted=false,load;
const prefs={'extensions.zotero.paperpilot.apiKey':'regression-placeholder'};
const settingsCtx={document:{getElementById:id=>mounted?elements.get(id):null,addEventListener(type,fn){if(type==='load')load=fn;},removeEventListener(){}},Zotero:{Prefs:{get:k=>prefs[k]}},setTimeout};
vm.runInNewContext(fs.readFileSync(new URL('../addon/chrome/content/scripts/settings.js',import.meta.url),'utf8'),settingsCtx);
assert.equal(elements.get('pp-apiKey').value,'');mounted=true;load({target:{id:'paperpilot-settings-root'}});
assert.equal(elements.get('pp-apiKey').value,'regression-placeholder');
console.log('PASS: settings wait for real fragment load and match actual input ids');
